POST http://localhost:3000/reports HTTP/1.1
Content-Type: application/json

{
    "make":"toyo",
    "model":"corolla",
    "year":1980,
    "mileage":10000,
    "lng":0,
    "lat":0,
    "price":50000
}

GET http://localhost:3000/reports HTTP/1.1